; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Common configuration for all ESP32 variants
[env]
platform = espressif32
framework = espidf
platform_packages =
    platformio/framework-espidf@~3.50500.0
lib_deps =
	jgromes/RadioLib@7.2.1
	h2zero/esp-nimble-cpp@2.1.1
lib_extra_dirs =
	~/.platformio/lib
	../shared
build_flags =
	-Wall
	-Wunused
	; LoRa configuration (RadioLib compatible)
	-DLORA_FREQUENCY=433.92
	-DLORA_BANDWIDTH=31.25
	-DLORA_SPREADING_FACTOR=11
	-DLORA_CODING_RATE=5
	-DLORA_TX_POWER=20
lib_ldf_mode = deep+
monitor_speed = 115200

[env:esp32dev]
board = esp32dev
build_flags =
	${env.build_flags}
	-DCPU_FREQ_MHZ=80
	-DLORA_SCK=18
	-DLORA_MISO=19
	-DLORA_MOSI=23
	-DLORA_SS=5
	-DLORA_RST=12
	-DLORA_DIO0=32
	-DLORA_BUSY=0
	-DLED_PIN=2
	-DWAKE_BUTTON=0
	-DDEVICE_NAME='"ESP32-LoRa"'
	-DRADIO_SX1278

[env:lilygo-t-display-s3]
board = lilygo-t-display-s3
build_flags =
	${env.build_flags}
	-DCPU_FREQ_MHZ=160
	-DLORA_SCK=12
    -DLORA_MISO=13
    -DLORA_MOSI=11
    -DLORA_SS=10
    -DLORA_RST=43
    -DLORA_DIO0=3
	-DLORA_BUSY=0
	-DWAKE_BUTTON=14
	-DDEVICE_NAME='"ESP32S3-LoRa"'
	-DRADIO_SX1278

;http://community.heltec.cn/t/heltec-v3-and-wsl-v3-i2c-pins/12382
[env:heltec-wifi-lora-v3]
board = heltec_wifi_lora_32_V3
build_flags =
	${env.build_flags}
	-DCPU_FREQ_MHZ=160
	-DLORA_SCK=9
    -DLORA_MISO=11
    -DLORA_MOSI=10
    -DLORA_SS=8
    -DLORA_RST=12
    -DLORA_DIO0=14
	-DLORA_BUSY=13
	-DLED_PIN=35
	-DWAKE_BUTTON=0
	-DDEVICE_NAME='"HellTecLite-LoRa"'
	-DRADIO_SX1262