[target.xtensa-esp32s3-none-elf]
runner = "espflash flash -c esp32s3 -s 16mb -m dio -f 80mhz --no-skip --monitor"

[env]
ESP_LOG = "INFO"
LORA_TX_POWER_DBM = "14"
LORA_TX_FREQUENCY = "433920000"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
