; Common configuration
[env]
monitor_speed = 115200
lib_deps =
	jgromes/RadioLib@7.7.1
	adafruit/Adafruit SleepyDog Library@^1.8.4
build_flags =
	-Wall
	-Wextra
	-DLORA_TX_POWER=22
	-DLORA_MAX_CURRENT=140
; -Wshadow applied only to project sources (libraries like RadioLib have their own shadow warnings)
build_src_flags =
	-Wshadow

; Heltec WiFi LoRa v3
; http://community.heltec.cn/t/heltec-v3-and-wsl-v3-i2c-pins/12382
[env:heltec-wifi-lora-v3]
# https://github.com/platformio/platform-espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
framework = arduino, espidf
board = heltec_wifi_lora_32_V3
board_build.partitions = default_8MB.csv
upload_speed = 921600
monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep+
lib_deps =
	${env.lib_deps}
	h2zero/NimBLE-Arduino@2.5.0
lib_extra_dirs = ~/.platformio/lib
check_tool = cppcheck
check_flags = cppcheck: --enable=all
check_severity = medium, high
check_skip_packages = yes
build_flags =
	${env.build_flags}
	-Wunused
	-DRADIO_SX1262
	-DLORA_SCK=9
	-DLORA_MISO=11
	-DLORA_MOSI=10
	-DLORA_SS=8
	-DLORA_RST=12
	-DLORA_DIO0=14
	-DLORA_BUSY=13
	-DLED_PIN=35
	-DWAKE_BUTTON=0
	-DVEXT_PIN=36
	-DBASE_DEVICE_NAME='"HellTecLite-LoRa"'
	-DBATTERY_ADC_PIN=1
	-DBATTERY_ADC_CTRL=37
	-DBATTERY_ADC_CTRL_ENABLED=LOW
	-DBATTERY_VOLTAGE_DIVIDER=5.1205

; Seeed XIAO nRF52840
[env:xiao_nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = arduino
board = seeed-xiao-afruitnrf52-nrf52840
lib_deps =
	${env.lib_deps}
build_src_filter =
	+<unified_main.cpp>
	+<common/*.cpp>
	+<nrf52/*.cpp>
debug_tool = cmsis-dap
debug_init_break = tbreak setup
build_flags =
	${env.build_flags}
	-DRADIO_SX1268
	-DLORA_SCK=D8
	-DLORA_MISO=D9
	-DLORA_MOSI=D10
	-DLORA_SS=D4
	-DLORA_RST=D2
	-DLORA_DIO0=D1
	-DLORA_BUSY=D3
	-DLED_PIN=LED_GREEN
	-DWAKE_BUTTON=D6
	-DBASE_DEVICE_NAME='"nRF52-LoRa"'
	-DBATTERY_ADC_PIN=PIN_VBAT
	-DBATTERY_ADC_CTRL=VBAT_ENABLE
	-DBATTERY_ADC_CTRL_ENABLED=LOW
	-DBATTERY_VOLTAGE_DIVIDER=3.0
	-DBATTERY_SENSE_RESOLUTION_BITS=12
